apiVersion: v1
kind: Secret
metadata:
  name: medusa-bucket-key
  namespace: k8ssandra-operator
type: Opaque
stringData:
  credentials: |-
    [default]
    aws_access_key_id = k8ssandra_key
    aws_secret_access_key = k8ssandra_secret
